### ISSUE TITLE
Repeated connection failure message on initial configuration flow

### ISSUE THREAD

**Issue by matobet** [matobet/moVirt#160] opened 2016-03-07 12:29 UTC
When configuring a fresh installation of moVirt in case the connection fails (for whatever reason: invalid certificate, host not found) the application displays several user unfriendly messages. 

This should be replaced by one higher-level (frendlier) message since we expect user to make a lot of mistakes in initial configuration.

**Comment by suomiy** [comment] 2016-03-07 15:37
I will look into it. How should higher-level message look like? Or should we show the first or last error only? Or compilation of those errors?

**Comment by matobet** [comment] 2016-03-07 16:03
Since the errors are usually the same (similar?) for the scope of 1.3 I'd say it's ok to show only the first. 
@jelkosz opinion?

**Comment by suomiy** [comment] 2016-03-11 20:41
is caused by automatic sync after account creation. Fixed in #161 
Shows only first error message for syncing - and then error for every logging attempt in auth activity. 
So it is possible to see maximally 2 errors at the same time

**Comment by suomiy** [comment] 2016-03-11 20:43
Or should we disable syncing errors completely in authenticator activity?

**Closed** 2016-03-14 15:14 UTC
Labels: bug
