### ISSUE TITLE
No refresh on connection lost

### ISSUE THREAD

**Issue by sandrobonazzola** [matobet/moVirt#66] opened 2015-05-25 06:12 UTC
Once you've connected moVirt app to the engine, if the connection goes down the app doesn't refresh the state keeping last state displayed.

For example you can see a VM still in start-up and the host up and running also if the engine has been disconnected 20 days before.

**Comment by sandrobonazzola** [comment] 2015-05-25 06:12
![screenshot_2015-05-16-19-09-50](https://cloud.githubusercontent.com/assets/937860/7792627/cb36f258-02b5-11e5-8be5-ad265bda917a.png)
![screenshot_2015-05-16-19-10-10](https://cloud.githubusercontent.com/assets/937860/7792628/cb3f8dbe-02b5-11e5-9fac-c422ea3b002a.png)
![screenshot_2015-05-16-19-10-42](https://cloud.githubusercontent.com/assets/937860/7792629/cb48cdf2-02b5-11e5-8ec3-88f0433feaae.png)

**Comment by jelkosz** [comment] 2015-05-25 06:35
@sandrobonazzola Hey Sandro! If you manually trigger the refresh (e.g. pull down) it starts working again or you need to restart the whole app?

**Comment by sandrobonazzola** [comment] 2015-05-25 16:15
manually triggering the refresh shows a rest request error. restarting the app or the phone doesn't update the state.

**Comment by jelkosz** [comment] 2015-05-26 06:31
@sandrobonazzola well, I can not simulate this so Im going to flood with with questions:
- when you go to Settings->Connection Settings ->press Save Account it should enforce re-login. If you do this, it helps?
- if not, are you sure the connection went back properly? e.g. if you try to access the same URL as configured in connection settings from mobile browser, can you access it?
- what android version do you have? There are some issues with certificates on android 4.1 so maybe with reconnect as well. But I have not seen it...

**Comment by sandrobonazzola** [comment] 2015-05-26 07:42
Please note that the server is unreachable, not up anymore on the same ip address.
The issue is that even if the engine is not reachable it still report host up and vm booting.

save account give an I/O error since the engine is not there anymore.
after the failure, the host is still reported up and the vm booting.

Android 4.4.2 - Samsung S5 mini

**Comment by jelkosz** [comment] 2015-05-26 07:46
ah, I finally understand! 
So the problem is not that moVirt does not reconnect after the engine is up again but that it does not notify you that he does not have a connection! 
OK, will fix that, thank you!

**Comment by jelkosz** [comment] 2015-06-26 10:56
fixed by: https://github.com/matobet/moVirt/pull/76/

**Closed** 2015-06-26 10:56 UTC
