### ISSUE TITLE
A crash report from user contains this stack trace

### ISSUE THREAD

**Issue by jelkosz** [matobet/moVirt#181] opened 2016-06-14 11:25 UTC
Needs investigation, the stack trace:

java.lang.IllegalStateException: Activity has been destroyed
	at android.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1350)
	at android.app.BackStackRecord.commitInternal(BackStackRecord.java:729)
	at android.app.BackStackRecord.commit(BackStackRecord.java:705)
	at android.app.DialogFragment.show(DialogFragment.java:230)
	at org.ovirt.mobile.movirt.ui.AuthenticatorActivity.showError(AuthenticatorActivity.java:364)
	at org.ovirt.mobile.movirt.ui.AuthenticatorActivity.finishLogin(AuthenticatorActivity.java:322)
	at org.ovirt.mobile.movirt.ui.AuthenticatorActivity_.access$201(AuthenticatorActivity_.java:43)
	at org.ovirt.mobile.movirt.ui.AuthenticatorActivity_$6.execute(AuthenticatorActivity_.java:233)
	at org.androidannotations.api.BackgroundExecutor$Task.run(BackgroundExecutor.java:401)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by suomiy** [comment] 2016-07-12 12:03
It was caused by closing login activity while login was still pending.

**Closed** 2016-07-27 12:43 UTC
